# Generated by Django 5.2.6 on 2025-09-19 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_text', models.TextField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filter.filter')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.ManyToManyField(to='filter.filter')),
            ],
        ),
    ]
